language: java
jdk:
- oraclejdk8
script: mvn clean package
notifications:
  slack:
    secure: UDZxTr4MYwKa9ZMW/5A7ng3FAY7FDZlFD4v8WVdcLvPewYp7buMD1/REM7aG0zBMuWr55Fc34wIrUlX1Kj3qlKE0AZZReGdaabezwNxrNtUHequn3/olQxB/ldOyN3JDDHDUDKL3wUYRFE5Ynta+M673LquqMnrkJx4v3zcrMch3pvuiNAmMWxT0ThmD/voWfcMR5ZidJF6NHxFnNjZ4AM7ciA+q2L7uYX8iHQzADHNPw3S0ceEG8OXbD1v+WN9rFIgXhW8a1/Pr/rsruV2r1NZW/lwRPo40Gx//srtY233p0GfQp9hO3jbbnEUC5XBYtGtAOEMNFHdcW6wlc9P7tbBHW9xbdXJY5A539SMMLUAJzo0DVSn8kTJ4kfA1F5BKOo26AIJPVB7Juc0uep1onn5hpy4GsfkQqhpSkz/PZOl8Q6ZKMH14iYoe+6zZOF6c/kHVHTrwpVCgelqJQZi+A9ojR0CfsLFRpbopWQlfFh+hyK4JAm/AofeehZcrj/jIjlruuWFVEJVDhF9AYWzMEebmgxFdjsAbTT38H4lNdcnVEtIOWBD8r1Es1QGT2Lbmk9FwZSYz7mMN+Mf3EBk+QRL9F2nbuIuDxs+LMbgxlRyCeGyumqYlo4unsuiRWfwADN+YcLE/e6sBCAeFS2urFaWOQC3zEBwdxgdu9Vb5Awc=
